### ISSUE TITLE
只能爬取200行，之后提示list out of range

### ISSUE THREAD

**Issue by zxy1987913** [Sglight/2bulu_scrapy#1]
您好，使用了您的代码爬取2bulu，但只能爬取200行，之后提示list out of range，请问下是什么原因啊？

**Comment by Sglight** [comment]
可以先尝试加入 try ... except，代码赶任务写的，所以很粗糙，目前也应该处于年久失修的状态，等周末我再看看怎么处理。

**Comment by Sglight** [comment]
@zxy1987913 大概是网站增加了反爬机制，最新的 commit 加了一个休眠机制，我尝试了下默认设置能爬 100 多页，后面就手动停止了，没继续尝试。
